### ISSUE TITLE
Add "verification" command

### ISSUE THREAD

**Issue by danieldeutsch** [naacl2022-reproducibility-track/naacl-utils#16]
I think it would be good to verify that the Beaker job outputs some expected text. I believe that @epwalsh said this would be most easily done via the naacl-utils API. I am imagining a use case like
```
naacl-utils verify <submission-id> <expected-output-txt>
```
The command would verify that the stdout from the submission ends with the contents of the text file (i.e., it's the last thing output by the Docker container).

When the users participate in the track, we can ask them for their submission IDs and the expected output files so we can manually run the verification ourselves.

Does this seem like it will work @epwalsh?

**Comment by epwalsh** [comment]
Yeup, I like that approach and it should be easy to implement.
