### ISSUE TITLE
Please add me to the NAACL Beaker organization

### ISSUE THREAD

**Issue by frankaging** [naacl2022-reproducibility-track/naacl-utils#52]
Hi, please add me to the NAACL Beaker organization.
- My Beaker username is: frankaging
- The title of my paper is: Causal Distillation for Language Models

## For admins :point_down:

*You can add this user to the Beaker NAACL organization by manually triggering the
[Beaker NAACL Add Member](https://github.com/naacl2022-reproducibility-track/naacl-utils/actions/workflows/naacl_add_member.yml) workflow.
Just click the "Run workflow" dropdown on the right, fill in the username, and then click the green "Run workflow" button. Once the job has completed you can close this issue.*

**Comment by danieldeutsch** [comment]
Added!
