### ISSUE TITLE
Add how to find your user token during `naacl-utils setup`

### ISSUE THREAD

**Issue by danieldeutsch** [naacl2022-reproducibility-track/naacl-utils#7]

**Comment by epwalsh** [comment]
Do you mean in the README? Because `naacl-utils setup` will give you the link where you can find it.
![image](https://user-images.githubusercontent.com/8812459/146067700-7ca7e3f7-ecd7-4205-a38e-0f82a66a8a0d.png)

**Comment by danieldeutsch** [comment]
Ah, right. Ok I think that's fine.
