### ISSUE TITLE
Updated image did not get pushed on submit

### ISSUE THREAD

**Issue by danieldeutsch** [naacl2022-reproducibility-track/naacl-utils#9]
I believe I did the following:
```
docker build -t my-image .
naacl-utils submit my-image test-1

# The job failed, so I modified my Dockerfile, then repeated the submission process
docker build -t my-image .
naacl-utils submit my-image test-2
```
The utils did not push any image and the old image ran. After I retagged my image with a new name and submitted that tag, it worked as expected.

I haven't tried to reproduce this so I may have just messed up somewhere.

**Comment by epwalsh** [comment]
Ah, you're right. This is a bug. PR coming soon.
