### ISSUE TITLE
Please add me to the NAACL Beaker organization

### ISSUE THREAD

**Issue by jakpra** [naacl2022-reproducibility-track/naacl-utils#91]
Hi, please add me to the NAACL Beaker organization.
- My Beaker username is: jakpra
- The title of my paper is: Linguistic Frameworks Go Toe-to-Toe at Neuro-symbolic Language Modeling

## For admins :point_down:

*You can add this user to the Beaker NAACL organization by manually triggering the
[Beaker NAACL Add Member](https://github.com/naacl2022-reproducibility-track/naacl-utils/actions/workflows/naacl_add_member.yml) workflow.
Just click the "Run workflow" dropdown on the right, fill in the username, and then click the green "Run workflow" button. Once the job has completed you can close this issue.*

**Comment by danieldeutsch** [comment]
Added!
